= Creating a Spring Boot Application with JPA
+
Load the data-jpa-spring-boot project into STS/Eclipse
+
[source, bash]
---------------------------------------------------------------------
CN-Workshop-Boeing-workspace:
├── labs
│   ├── lab03
│   │   ├── data-jpa-spring-boot
---------------------------------------------------------------------

This application will create a simple reading list by asking for books you have read and storing them in a simple relational repository. The first stereotype we will need is the domain model itself, which is Book.

== Add the domain object - Book
. Add a Book object to the io.pivotal package with the required JPA annotations.
+
[source, java]
---------------------------------------------------------------------

package io.pivotal;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

@Entity
public class Book {

	@Id
	@GeneratedValue(strategy=GenerationType.AUTO)
	private Long id;
	private String reader;
	private String isbn;
	private String title;
	private String author;
	private String description;

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getReader() {
		return reader;
	}

	public void setReader(String reader) {
		this.reader = reader;
	}

	public String getIsbn() {
		return isbn;
	}

	public void setIsbn(String isbn) {
		this.isbn = isbn;
	}

	public String getTitle() {
		return title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getAuthor() {
		return author;
	}

	public void setAuthor(String author) {
		this.author = author;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
---------------------------------------------------------------------

== Add an Repository in a separate Repository class that we'll name ReadingListRepository

. We extend a JpaRepository with our domain type and key type as parameters in  class _io.pivotal.ReadingListRepository_ (/data-jpa-spring-boot/src/main/java/io/pivotal/ReadingListRepository.java).

[source, java]
---------------------------------------------------------------------
package io.pivotal;

import java.util.List;
import org.springframework.data.jpa.repository.JpaRepository;

public interface ReadingListRepository extends JpaRepository<Book, Long> {

	List<Book> findByReader(String reader);

}
---------------------------------------------------------------------

== Add an Endpoint in a separate Controller class that we'll name ReadingListController

. Add an @RestController annotation to the class _io.pivotal.ReadingListController_ (/data-jpa-spring-boot/src/main/java/io/pivotal/ReadingListController.java).
+
[source, java, numbered]
---------------------------------------------------------------------
package io.pivotal;

import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

@Controller
@RequestMapping("/readingList")
public class ReadingListController {

  private static final String reader = "craig";

	private ReadingListRepository readingListRepository;

	@Autowired
	public ReadingListController(ReadingListRepository readingListRepository) {
		this.readingListRepository = readingListRepository;
	}

	@RequestMapping(method=RequestMethod.GET)
	public String readersBooks(Model model) {

		List<Book> readingList = readingListRepository.findByReader(reader);
		if (readingList != null) {
			model.addAttribute("books", readingList);
		}
		return "readingList";
	}

	@RequestMapping(method=RequestMethod.POST)
	public String addToReadingList(Book book) {
		book.setReader(reader);
		readingListRepository.save(book);
		return "redirect:/readingList";
	}
}

---------------------------------------------------------------------

. Add a web page so that we can see the book titles provided in an html thymeleaf page called _readingList.html_ (/data-jpa-spring-boot/src/main/resources/templates/readingList.html).
+
[source,html]
---------------------------------------------------------------------
<html>
  <head>
    <title>Reading List</title>
    <link rel="stylesheet" th:href="@{/style.css}"></link>
  </head>

  <body>
    <h2>Your Reading List</h2>
    <div th:unless="${#lists.isEmpty(books)}">
      <dl th:each="book : ${books}">
        <dt class="bookHeadline">
          <span th:text="${book.title}">Title</span> by
          <span th:text="${book.author}">Author</span>
          (ISBN: <span th:text="${book.isbn}">ISBN</span>)
        </dt>
        <dd class="bookDescription">
          <span th:if="${book.description}"
                th:text="${book.description}">Description</span>
          <span th:if="${book.description eq null}">
                No description available</span>
        </dd>
      </dl>
    </div>
    <div th:if="${#lists.isEmpty(books)}">
      <p>You have no books in your book list</p>
    </div>


    <hr/>

    <h3>Add a book</h3>
    <form method="POST">
      <label for="title">Title:</label>
        <input type="text" name="title" size="50"></input><br/>
      <label for="author">Author:</label>
        <input type="text" name="author" size="50"></input><br/>
      <label for="isbn">ISBN:</label>
        <input type="text" name="isbn" size="15"></input><br/>
      <label for="description">Description:</label><br/>
        <textarea name="description" cols="80" rows="5"></textarea><br/>
      <input type="submit"></input>
    </form>

  </body>
</html>
---------------------------------------------------------------------

. Add a simple style sheet to make our page look like a UI engineer has labored over it by placing the style sheet in  (/data-jpa-spring-boot/src/main/resources/static/style.css).


```css
vvbody {
	background-color: #cccccc;
	font-family: arial,helvetica,sans-serif;
}

.bookHeadline {
	font-size: 12pt;
	font-weight: bold;
}

.bookDescription {
	font-size: 10pt;
}

label {
	font-weight: bold;
}
```


Completed:  Our main only has the role of bootstrapping the application.
+

[source,java]
---------------------------------------------------------------------
package io.pivotal;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class DataJpaSpringBootApplication {

	public static void main(String[] args) {
		SpringApplication.run(DataJpaSpringBootApplication.class, args);
	}
}
---------------------------------------------------------------------

== Run the _data-jpa-spring-boot_ Application

. In a terminal, change working directory to *CN-Workshop-Boeing-workspace/labs/lab03/data-jpa-spring-boot*
+
$ cd CN-Workshop-Boeing-workspace/labs/lab03/data-jpa-spring-boot

. Run the application
+
$ mvn clean spring-boot:run

. You should see the application start up an embedded Apache Tomcat server on port 8080 (review terminal output):
+
[source,bash]
---------------------------------------------------------------------
2015-10-02 13:26:59.264  INFO 44749 --- [lication.main()] s.b.c.e.t.TomcatEmbeddedServletContainer: Tomcat started on port(s): 8080 (http)
2015-10-02 13:26:59.267  INFO 44749 --- [lication.main()] io.pivotal.DataJpaSpringBootApplication: Started DataJpaSpringBootApplication in 2.541 seconds (JVM running for 9.141)
---------------------------------------------------------------------

. Browse to http://localhost:8080/readingList

. Stop the _data-jpa-spring-boot_ application. In the terminal window: *Ctrl + C*

== Set up the Rest Repository

Spring Boot includes a number of additional features to help you monitor and manage your application when it’s pushed to production. These features are added by adding _spring-boot-starter-data-rest_ to the classpath.

. Add the Spring Boot Rest dependency the following file: /data-rest-spring-boot/pom.xml
+
[source, xml]
---------------------------------------------------------------------
<dependency>
	<groupId>org.springframework.boot</groupId>
	<artifactId>spring-boot-starter-data-rest</artifactId>
</dependency>
---------------------------------------------------------------------

. Add a ReadingListRestRepository with the following file
[source, java]
---------------------------------------------------------------------
package io.pivotal;

import java.util.List;

import org.springframework.data.repository.CrudRepository;
import org.springframework.data.repository.query.Param;

public interface ReadingListRestRepository extends CrudRepository<Book, Long> {

       List<Book> findByReader(@Param("reader") String reader);

}
---------------------------------------------------------------------

. Run the updated _data-rest-spring-boot_ application:
+
$ mvn clean spring-boot:run
+
Try out the following endpoints. The output is omitted here because it can be quite large:
+
http://localhost:8080/books
+
Search for a reader
+
http://localhost:8080/books/search/findByReader?reader=craig

== Deploy _data-jpa-spring-boot_ to Pivotal Cloud Foundry

. Build the application
+
[source,bash]
---------------------------------------------------------------------
$ mvn clean package
---------------------------------------------------------------------

. Create an application manifest in the root of the project

. Add application metadata
+
[source, bash]
---------------------------------------------------------------------
---
applications:
- name: data-jpa-spring-boot
  host: data-jpa-spring-boot-${random-word}
  memory: 512M
  instances: 1
  path: ./target/data-jpa-spring-boot-0.0.1-SNAPSHOT.jar
  buildpack: java_buildpack
---------------------------------------------------------------------

. Push application into Cloud Foundry
+
$ cf push -f manifest.yml

. Find the URL created for your app in the health status report. Browse to your app.
